spring:
  datasource:
    url: jdbc:h2:mem:jobappdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  flyway:
    enabled: true
    url: jdbc:h2:mem:jobappdb
    user: sa
    password:
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: on
logging:
  level:
    org:
      flywaydb: debug
